### ISSUE TITLE
Potential issue: may some games be affected by this?

### ISSUE THREAD

**Issue by Ptival** [Codeusa/SteamCleaner#15]
I am not sure whether it was related to using the tool, but I've had two games fail to launch and complain about file integrity since using this tool.

The games were:
http://store.steampowered.com/app/55150/
which I had installed but never launched

and:
http://store.steampowered.com/app/271590/
which I had installed and launched

It could just be that my hard drive is misbehaving though... :(

**Comment by Thristle** [comment]
try
1.check for file integrity and fix using the steam client
2.see that the game now runs
3.use the cleaner and see if it cleans those game folders
4.if the game now fails to start report again

easiest fix is just adding a blacklist to the program (maybe one that is updated regulerly?)
