### ISSUE TITLE
Clean up Ren'Py runtimes for other systems

### ISSUE THREAD

**Issue by denilsonsa** [Codeusa/SteamCleaner#16]
There are [several visual novels on Steam][vn], such as [this one][s]. Many (most?) of them are built using [Ren'Py][rp] tool, and may include runtimes for Linux and Mac OS X. SteamCleaner could delete such runtimes and save about half-hundred megabytes.

![image](https://cloud.githubusercontent.com/assets/121676/12230244/21624020-b836-11e5-9de9-aabde89f342e.png)

(screenshot of [TreeSize Free][t] tool)

[s]: http://store.steampowered.com/app/429940/
[vn]: http://store.steampowered.com/tag/en/Visual%20Novel/
[rp]: http://www.renpy.org/
[t]: http://www.jam-software.de/treesize_free/

**Comment by Codeusa** [comment]
Disgusting, will add a wayt to detect them later.

**Comment by Codeusa** [comment]
So it seems to me a lot of these games ignore if you have Python installed and their executables rely on their bundled version, which is annoying, however, I will delete the runtimes for the other os's that don't matter.

**Comment by Codeusa** [comment]
![alldone](http://i.andrew.im/b9kf30.png)

All done.
