### ISSUE TITLE
Cannot handle symlinks

### ISSUE THREAD

**Issue by Causeless** [Codeusa/SteamCleaner#2]
A .NET error appears once it sees a symlink, often used when using RAM-disks for Steam games.

**Comment by KIPdeKIP** [comment]
This should be easily reproducible by using the application [Steam Mover](http://www.traynier.com/software/steammover). It moves any folder to another location and creates a symlink to point to the new location.

**Comment by Thristle** [comment]
i just tried it with steam mover and no error is showing up. can you try again and upload an image of the error with all the information?

**Comment by Causeless** [comment]
I apologize - I think the error is that there is a symlink to a location that doesn't exist, created by Dimmdrive. A way to skip "dead" symlinks could be useful, though, instead of the program shutting down completely.

**Comment by Codeusa** [comment]
On the latest version it should skip things that don't exist.
