### ISSUE TITLE
Can't run anything past 1.7, OR delete it.

### ISSUE THREAD

**Issue by SgtSARS** [Codeusa/SteamCleaner#20]
Versions 1.8 and 1.9 don't respond when I open them.  The Explorer window that I have open when running as administrator freezes, and task manager shows multiple instances of SteamCleaner.exe running in the Details tab.  I cannot delete these copies of steam cleaner because it says they are currently in use, and I can't stop the task manager processes because it says my access is denied, even after I changed the user security permissions in the properties window. No SteamCleaner window opens.  No log file is created.  Version 1.7 and earlier work flawlessly. Using Windows 10.

EDIT: Was able to delete files using the program Unlocker.  Tried again with fresh 1.9 download, repeated same issue.

**Comment by Codeusa** [comment]
Are you able to run it from source?

**Comment by SgtSARS** [comment]
Yes, it does load when I open it through steam.  Is this working as intended?

**Comment by Codeusa** [comment]
Try the latest version
