### ISSUE TITLE
Battlenet analyzer path

### ISSUE THREAD

**Issue by steveadoo32** [Codeusa/SteamCleaner#25]
It looks like the product path won't work, you do this:
`var productPath = GetBattleNetPath() + GetProductDbPath();`

but GetProductDbPath already does this:
```
private string GetProductDbPath() 
{
    return Path.Combine(GetBattleNetPath(), "\\Agent\\product.db");
}
```

**Comment by Codeusa** [comment]
So here is some weird behavior 

![](http://i.andrew.im/0wyxia.png)

Using the getProducDb path alone

![](http://i.andrew.im/ftlbf8.png)

Fixed by doing 
```csharp
  return Path.Combine(GetBattleNetPath(),
                "Agent\\product.db");
```
Instead, seems Path.Combine will always return the second argument is it begins with \\, / or \ literal.

We learn something new every day.
