### ISSUE TITLE
Steam library not found if default location doesn't exist

### ISSUE THREAD

**Issue by campbeb** [Codeusa/SteamCleaner#27]
When I run SteamCleaner, it doesn't find my Steam games.

The problem is that the program assumes a `common` folder exists where Steam is installed, but I don't have one there (I didn't manually remove it, it just isn't there).

![image](https://cloud.githubusercontent.com/assets/1089399/12867379/f4928954-ccb9-11e5-900a-1dac497153f1.png)

`AnalyzerService::FindPaths` tries to lookup a directory that doesn't exist, an exception is thrown, and the loop for looking up Steam games gets exited before my actual path gets processed.
```
Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
Could not find a part of the path 'C:\Program Files (x86)\Steam\SteamApps\common'.
```

**Comment by karasuhebi** [comment]
This happens to me too. Version 2.0 works fine but 2.1 fails.
