### ISSUE TITLE
Removes Penumbra

### ISSUE THREAD

**Issue by virtyvoid** [Codeusa/SteamCleaner#32]
Some games like Penumbra: Overture contain their files in directory named redist and thus will be removed by this cleaner.

> ...\SteamApps\common\Penumbra Overture\redist\sounds\boat_level\boat_fishing_loop1.ogg    76,429 KB
> ...\SteamApps\common\Penumbra Overture\redist\sounds\boat_level\boat_horn.snt 305 B
> ...\STEAM\SteamApps\common\Penumbra Overture\redist\sounds\boat_level\boat_horn1.ogg  109,455 KB
> ...\STEAM\SteamApps\common\Penumbra Overture\redist\sounds\boat_level\boat_wave_loop.snt  309 B
> ...\STEAM\SteamApps\common\Penumbra Overture\redist\sounds\boat_level\boat_wave_loop1.ogg 281,414 KB

**Comment by murrayc43** [comment]
I have tested and confirm this issue. A potential fix may be to first check the file extensions located in the directories and depending on if it's a certain type of file (ex: .ogg), assume it is being used and do not delete it?

I can see some problems arise with this method but doing a test with some other games, it looks like the majority are .cab files.

**Comment by Jurigag** [comment]
The same thing is for penumbra black plague, can you reopen this? @Codeusa
