### ISSUE TITLE
Scanning of Steam Libraries

### ISSUE THREAD

**Issue by BigBodZod** [Codeusa/SteamCleaner#33]
It appears that the various SteamLibrary directories do not get scanned or some of them get missed.

I've found numerous installed games where the redist folder is still there along with the DX and various pre-requisites are stored.

**Comment by BigBodZod** [comment]
I did some more testing and it appears the app is actually finding some of my Steam Library folders but not all of them or is not scanning them at all for some reason.

I have multiple library folders named as follows:

SteamLibrary1 through SteamLibrary6

**Comment by Codeusa** [comment]
Try running as admin.

**Comment by BigBodZod** [comment]
I will try that, but my current user account is a local admin account.

So I will do the run as trick and see if it makes any difference or not.

**Comment by fedexist** [comment]
I have this issue too. My default steam library is on a different disk wrt the steam installation and, even if I run the exe as admin, it does not even get scanned and appears on the located paths (whereas Origin, Gog and Uplay work fine as far as I can tell).
