### ISSUE TITLE
Battle.net games issue?

### ISSUE THREAD

**Issue by Stanzilla** [Codeusa/SteamCleaner#34]
Not really sure but those exe files should actually not be deleted, it will download them again anyway though?
![steamcleaner_2016-04-18_06-32-03](https://cloud.githubusercontent.com/assets/75278/14593797/68ac128a-052f-11e6-9d32-685f436ce04c.png)

**Comment by Codeusa** [comment]
I will fix this today.

**Comment by Stanzilla** [comment]
@Codeusa ok :D
