### ISSUE TITLE
Doesn't Find Anything besides Battle.net

### ISSUE THREAD

**Issue by MonthOLDpickle** [Codeusa/SteamCleaner#35]
And there isn't anything to clean there. But I have steam (uplay too) installed.

**Comment by JustThat70** [comment]
Try creating an empty folder named "common" in C:\Program Files (x86)\Steam\steamapps

**Comment by MonthOLDpickle** [comment]
I have steam installed in another location, is this the issue?

**Comment by MonthOLDpickle** [comment]
> Try creating an empty folder named "common" in C:\Program Files (x86)\Steam\steamapps

What if your steam isn't at default install location?

**Comment by JustThat70** [comment]
One thing to try might be creating the entire set of empty folders.

Create "Steam" in C:\program files (x86)
Then create "steamapps" inside that
then create "common" inside that

I know this isn't ideal, but it might work.
