### ISSUE TITLE
No Detection of Steam?

### ISSUE THREAD

**Issue by odiefrom** [Codeusa/SteamCleaner#36]
I have two Steam libraries on my PC, one on the D:\ which I don't expect it to find on it's own (is there a way to point it at a library?), and the default location on my C:.  Neither is found, it just tells me it found paths for Battle.net and GOG.  Any way to get it to find my file paths?

**Comment by JustThat70** [comment]
This defect (https://github.com/Codeusa/SteamCleaner/issues/27) may not be totally corrected. The workaround of creating an empty "common" folder in C:\Program Files (x86)\Steam\steamapps worked for me.

**Comment by odiefrom** [comment]
Bingo!  Created the C:\Program Files (x86)\Steam\steamapps\common directory got it to detect the library on my D drive.  Thanks @JustThat70
