### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by l0wBoB** [Codeusa/SteamCleaner#37]
Crashes on Startup when symlinks point to drives no longer connected. (i.e. RAMdisks)
Similar Problem as in #17 and #19.

[UnhandledException_22.04.2016.txt](https://github.com/Codeusa/SteamCleaner/files/232474/UnhandledException_22.04.2016.txt)

**Comment by thefinalhack** [comment]
Same issue of crash on startup and similar looking error log here.

[UnhandledException_28-12-2016.txt](https://github.com/Codeusa/SteamCleaner/files/676332/UnhandledException_28-12-2016.txt)
