### ISSUE TITLE
No Steam folders detected at all.

### ISSUE THREAD

**Issue by WalrusInAnus** [Codeusa/SteamCleaner#38]
It seems like the program isn't able to detect Steam at all. Maybe it's related to the fact I have all the games installed on different partitions.
Also, I think it would be nice if it was able to clean non-game junk files (same applies to Origin).

**Comment by Codeusa** [comment]
Did you try running it as administrator

**Comment by WalrusInAnus** [comment]
I am running an administrator account, so yes.
It detects Origin, but not Steam.

**Comment by DanteMackie** [comment]
#27 Create an empty 'common' folder at C:\Program Files (x86)\Steam\steamapps
That should fix it.

**Comment by WalrusInAnus** [comment]
That folder is already there (and has been since the beginning). It contains libraryfolders.vdf which defines all the libraries I use.

**Comment by DanteMackie** [comment]
Have you tried older versions to see if that works?

**Comment by WalrusInAnus** [comment]
You don't seem to be the author of the program, so I won't waste time replying to blind suggestions that don't do anything.

**Comment by MrJimmyPenguin** [comment]
Same here, no steam folders found at all, doesn't even mention steam under the game paths

**Comment by MrJimmyPenguin** [comment]
on the other post, simply making a folder "common" on c drive where it would be if you installed games on that drive made it discover all other folders.

**Comment by fa2X** [comment]
As @MrJimmyPenguin said, create the 'common' folder in the Steam folder NOT your games... ie- _C:\Program Files (x86)\Steam\steamapps\common_
