### ISSUE TITLE
Only default path is supported

### ISSUE THREAD

**Issue by ThereWasADream** [Codeusa/SteamCleaner#4]
Program encounters error if games are not installed at the default location OR simply does not detect my install location. A few others reported this happening on Reddit. Possible Windows 10 issue. Compatibility mode was tried and failed for all OS's selected.

(By the way, the whole internet thinks you are a total bro for doing this kind of stuff)

**Comment by psbj** [comment]
I've experienced this as well, though an easy workaround is to simply create the "common" folder inside the default directory and it should work fine.

**Comment by Codeusa** [comment]
Can you please share your config.vdf
