### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by Brigapes** [Codeusa/SteamCleaner#50]
Hi, not sure if related to https://github.com/Codeusa/SteamCleaner/issues/46 but i don't get any error message or a log.

http://i.imgur.com/H2TeDGs.png

I remember an older version a long time ago worked flawlessly.

Edit: Running with Admin priviliges. Any other PC related info you need, im happy to provide.

**Comment by bawaaaaah** [comment]
This crash appear when you have registry key for the application but the directory was removed
I have fix it #54

If you want try the patch, I have published a compiled version.
https://github.com/bawaaaaah/SteamCleaner/releases/tag/2.3.1

**Comment by Brigapes** [comment]
Works perfectly now!
