### ISSUE TITLE
Crash on startup, not even a window gets created

### ISSUE THREAD

**Issue by karasuhebi** [Codeusa/SteamCleaner#57]
According to Event Viewer the crash is being caused by d3d9.dll but I haven't had any crashes other than Steam Cleaner. Any ideas on what I could try?

**Comment by Willlux** [comment]
Make sure you don't have RTSS' OSD on as it interferes with this program.

**Comment by karasuhebi** [comment]
Yeah I believe that's what ended up fixing it, excluding it from RTSS. Thank you!
