### ISSUE TITLE
Windows 8.1 smartscreen prevents v1.1 from opening

### ISSUE THREAD

**Issue by yakka34** [Codeusa/SteamCleaner#7]
64bit
Windows 8.1

**Comment by KIPdeKIP** [comment]
Same thing happens on 64-bit Windows 10. I can tell SmartScreen it should run it anyway and it'll remember to run it. This should be possible on Windows 8.1 as well.

I can't get the SmartScreen popup to appear again. I'll see if I can find a picture with the run anyway function.

**Comment by recurzive** [comment]
The SmartScreen just notifies you about that, this program doesn't have good, as I know **Appication Reputation**. To increase this, the program itself needs to be signed or distributed widely.

Further information about this topic:
https://blogs.msdn.microsoft.com/ie/2012/08/14/microsoft-smartscreen-extended-validation-ev-code-signing-certificates/

**Comment by Codeusa** [comment]
Nothing can be done outside of signing and I don't  want to buy a cert so won't fix
