### ISSUE TITLE
No detection of games folders

### ISSUE THREAD

**Issue by renaclerican35** [Codeusa/SteamCleaner#71]
Hi !

I installed the games on other hard drives and SteamCleaner didn't look them.
How to do to specify directories on other hard drives ?
Thank you very much.

**Comment by Zorrototo** [comment]
You can't. Explain more in details your setup, where you installed what, and so on, this way it can maybe be fixed. I have multiple Steam libraries for example and it seems to look for and find them.

**Comment by MessiahMozgus** [comment]
It definitely isnt seeing my E and F drive steam libraries. Only D.

**Comment by Zorrototo** [comment]
Same as above then.

Anyway this tool is coming to an end, as mostly all Steam games have shifted to the new distribution system for redistributable package so.. there is no real point in using it anymore, in my opinion, as most games do not distribute these packages anymore within game files, they use the common one from Steam instead.

**Comment by Ryusennin** [comment]
Why do you feel the need to rant? Go use TikiOne instead.

Anyway, this is a NON issue as those redistributable files (shared or not) are still useless. Steam will not check for them anymore once your game is installed. I have more than a hundred games in my library and none of them was forced to be reinstalled after clearing the redistributable files.

**Comment by Zorrototo** [comment]
The redistributable are not useless if keeping one copy (the unique shared one) avoids other games to download them to then delete them. At this point it is only a question of 'do I keep these unique files?' or 'do I download (then use the tool to delete) again and again the unique redistributable file?'. In my opinion it is obvious that the tool purpose is questionable for Steam games now, as if users want to remove the shared redistributable they only need to delete the centralized folder, as redistributable file are not duplicated in each and every game installed but centralized in a unique folder now for Steam..

Also, there is no rant here, only you coming there weeks later to rant about imaginary rant.
