### ISSUE TITLE
Status showed 3000 gb when my disk is 2000 gb

### ISSUE THREAD

**Issue by maximxlss** [Codeusa/SteamCleaner#77]
Screenshot -https://cdn.discordapp.com/attachments/445247633322147840/616694573623934979/unknown.png

**Comment by CapoFantasma97** [comment]
That's 3,539 GB (3.539GB) not 3 thousands GB. It might depend on your language and locations settings on your computer.
Comma is used as a decimal separator instead of a dot in many countries.
